### ISSUE TITLE
Code Editor: Allow line/column-wise annotation of errors and messages

### ISSUE THREAD

**Issue by alex-ketch** [stencila/designa#157]
To avoid polluting the `outputs` section, mimic usual code editing experience, and closer position errors/messages to their location in the source code.

**Comment by nokome** [comment]
I just wanted to add an example of why I think this is quite a high priority. The following is a screenshot from an [eLife ERA](https://elife.stencila.io/article-55650/).  This code chunk executes successfully but display two warnings in the outputs:

![image](https://user-images.githubusercontent.com/1152336/110843727-7c68f980-830d-11eb-80ff-e672fb9b1d0b.png)

For the reader, this makes it looks like something has gone wrong.

An alternative would be to:
- place the warnings (or errors) at the bottom of the code editor (non editable but styled using same font etc as editor)
- perhaps, add a warning (or error) icon next to the side-by-side view icon or even next to the eye icon - so an author can quickly scan to see which code chunks have errors/warnings without having to open each the code for each chunk.

I propose that we make these changes as a first step and then later see if we can position the errors on the relevant line.

**Comment by alex-ketch** [comment]
I can take a stab at it tomorrow @nokome, shouldn't be too much trouble if we do something like this: https://codemirror.net/6/examples/panel/#dynamic-panel-content
