### ISSUE TITLE
CodeChunk: errors when typing more than one line

### ISSUE THREAD

**Issue by nokome** [stencila/designa#25]
The following error occurs regardless of the language selected or the text entered. The first error happens on the first keypress after the new line, the others on subsequent keypresses. This is a high priority bug because it makes the component useless for anything other than single line snippets of code.

![image](https://user-images.githubusercontent.com/1152336/68565358-1de10080-04b8-11ea-9fd2-20b6389ba691.png)

![image](https://user-images.githubusercontent.com/1152336/68565387-36511b00-04b8-11ea-8a58-4ba106f4349c.png)

**Comment by alex-ketch** [comment]
This is [an upstream issue](https://github.com/codemirror/codemirror.next/issues/135) and will be fixed with an upcoming release.

Meanwhile we can instantiate the editor with placeholder text to work around it

**Comment by nokome** [comment]
Wondering, is this resolved? I tried to test using https://stencila.github.io/designa/?path=/story/molecules-code-chunk--single-code-chunk but that seems to be broken?

**Comment by alex-ketch** [comment]
Seems a release was never made. Closed by https://github.com/stencila/designa/pull/30/commits/4c84795898c985452b7c8f07249b924e5bf27faa
