### ISSUE TITLE
Expose current Schema node `status` property of executable nodes as part of component UI

### ISSUE THREAD

**Issue by alex-ketch** [stencila/designa#250]
To provide visibility into node execution status, we'd like to add a status property to various executable Schema nodes (i.e. Code & Math) based nodes.

Depends on https://github.com/stencila/stencila/issues/1251 being completed first.

**Comment by nokome** [comment]
Several properties have been added to `CodeChunk` and `CodeExpression` (via the [`CodeExecutable` base type](https://github.com/stencila/schema/blob/master/schema/CodeExecutable.schema.yaml)): `compileDigest`, `executeDigest`, `executeStatus`, `executeEnded` and `executeDuration`. An example of the encoding for a `CodeChunk`:

```html
<stencila-code-chunk
    itemtype="http://schema.stenci.la/CodeChunk" itemscope="" id="cc-1"
    programming-language="calc"
    compile-digest="tbwf_ZCRL7GL7259gJCRksemSSiWMgFW1n-68QTGVEo.6n7aj6ejT9qhLyTucvtLVqYbqy0bkcxA-y7azALl03M..0"
    execute-digest="tbwf_ZCRL7GL7259gJCRksemSSiWMgFW1n-68QTGVEo.6n7aj6ejT9qhLyTucvtLVqYbqy0bkcxA-y7azALl03M..0"
    execute-status="Succeeded"
    execute-ended="2022-01-10T08:43:39.417734048+00:00"
    execute-duration="0.002131382"
>
```

The `compileDigest` and `executeDigest` are used internally to calculate which nodes are "stale" and need to be re-executed. However, they also encompass information that can be used to convey to the users the execution state of of nodes with respect to one another and the kernel. Here's a description of the four parts of those diests from the Rust code:

```rust
/// A digest representing the state of a [`Resource`] and its dependencies.
///
/// The digest is separated into several parts. Although initially it may seem that the
/// parts are redundant ("can't they all be folded into a single digest?"), each
/// part provides useful information. For example, it is useful, to store
/// the `content_digest`, in addition to `semantic_digest`, to be able
/// to indicate to the user that a change in the resource has been detected but
/// that it does not appear to change its semantics.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct ResourceDigest {
    /// A digest that captures the content of the resource (e.g the `text`
    /// of a `CodeChunk`, or the bytes of a file).
    pub content_digest: String,

    /// A digest that captures the "semantic intent" of the resource
    /// with respect to the dependency graph.
    ///
    /// For example, for `Code` resources it is preferably derived from the AST
    /// of the code and should only change when the semantics of the code change.
    pub semantic_digest: String,

    /// A digest of the `dependencies_digest`s of the dependencies of a resource.
    ///
    /// If there are no dependencies then `dependencies_digest` is an empty string.
    pub dependencies_digest: String,

    /// The count of the number of code dependencies that have a `compile_digest` that
    /// is unequal to the `execute_digest` (i.e. are out of sync with the `KernelSpace`).
    ///
    /// If there are no dependencies then `dependencies_unsynced` is zero. May include
    /// duplicates for diamond shaped dependency graphs so this represents a maximum number.
    pub dependencies_unsynced: u32,
}
```

I propose that the components UIs for `CodeChunk` and `CodeExpression` represent, through icons / colors / messages, indicate each node as being in one of these states:

1. Not yet run
2. Re-run required, semantics have changed
3. Re-run required, one or more dependencies have changed
4. Re-run required, one or more dependencies was out of sync with kernel
5. Scheduled [the node is scheduled to be executed but not yet running; cancellable]
6. Running [cancellable]
7. Succeeded `executeEnded` ago in `executeDuration`
8. Failed `executeEnded` ago after `executeDuration`
9. Cancelled `executeEnded` ago after `executeDuration`

Here, `executeEnded` and `executeDuration` would be "humanized" e.g. "11s ago in 23s".

The pseudocode for which of theses states is in is roughly:

1.  `executeStatus === undefined`
2. `compileDigest[1] !== executeDigest[1]`
3. `compileDigest[2] !== executeDigest[2]`
4. `executeDigest[3] !== "0"`
5. `executeStatus === "Scheduled"`
6. `executeStatus === "Running"`
7. `executeStatus === "Succeeded"`
8. `executeStatus === "Failed"`
9. `executeStatus === "Cancelled"`

**Comment by alex-ketch** [comment]
Thanks for this @nokome 💖
The above logic sounds good, however for the UI I think it makes sense to represent the digest/compilation change status independently from the Succeeded/Failed status.
This way we can have a node that has both `re-run required (semantics/deps)` and `executeStatus === "Failed"`.
Will explore designs and share for feedback.

**Comment by alex-ketch** [comment]
@nokome wanted to confirm before I refactor the logic, the re-run required logic should now use the `executeRequired` value rather than comparing the digests?

**Comment by nokome** [comment]
Sorry, just saw this. 

> the re-run required logic should now use the executeRequired value rather than comparing the digests?

Yes. Note also though that `executeRequired` can be `No` (chunk and it's deps not stale) but `executeStatus` is `Failed` (error in code).
