### ISSUE TITLE
CodeExpression: add a programmingLanguage property

### ISSUE THREAD

**Issue by nokome** [stencila/designa#38]
Curently `CodeExpression` component does not have a `programmingLanguage` property which it inherits from [`Code`](https://github.com/stencila/schema/blob/master/schema/Code.schema.yaml) as does `CodeChunk`.

**Comment by nokome** [comment]
This is still an issue and means that `CodeExpressions` can not be executed because when they are sent to Executa, they lack `programmingLanguage` property that allows them to be delegated to the correct language interpreter (currently they are returned unexecuted):

![image](https://user-images.githubusercontent.com/1152336/90306888-81a3c880-df25-11ea-9801-8da1bc07bafc.png)


Note that currently, Encoda is encoding code expressions in HTML with the `programming-language="r"` attribute, which is inconsistent with `data-programminglanguage="r"` that is used for code chunks:

```html
<stencila-code-expression programming-language="r" itemscope=""
  itemtype="http://schema.stenci.la/CodeExpression"><code class="r"
  slot="text">length(subset(data2, Lot==1 &amp; Time==0)$value)</code><output
  slot="output"><span data-itemtype="http://schema.org/Number">3</span></output>
</stencila-code-expression>
```

**Comment by nokome** [comment]
Thanks for this @alex-ketch, what should the HTML attribute be for both `CodeChunk`s and `CodeExpression`s: `programming-language` or `data-programminglanguage`?

**Comment by alex-ketch** [comment]
Right now there's a discrepancy, but ideally it should be `programming-language` for both.
Will log an issue in Encoda to make the change.
