### ISSUE TITLE
[Proposal]: Style & Design Systems

### ISSUE THREAD

**Issue by alex-ketch** [stencila/designa#9]
We have a few active projects with differing style requirements, and more projects are likely to come in the future. 

To keep development manageable, consistent, and streamlined, I propose structuring this project into following areas of concern:
- Structural & Layout styles
- Brand Assets
- Visual Modifiers:
	- Stencila design system
	- Stencila themed Material Design system
        - Stencila themed Microsoft Fabric design system

The big question is, how important is it for us to share work between the different visual layers? Do we instead fully invest in a third party design system, and can we even do that considering the list of targets above?

## Proposal

I suggest we use [Tailwind](https://tailwindcss.com) to skip the first layer of structural/layout styling. The composable nature lends itself well to building custom designs while abstracting away a lot of the boilerplate. This means we can we can delegate a lot of the structural/layout to an existing framework, letting us concentrate on fleshing out our own design system (the Visual Modifiers part).
The ability to [extract component level classes](https://tailwindcss.com/docs/extracting-components) from identified patterns will help with consistency within and across projects, as well as allow us to create themed variants for different visual styles.
The components should be built up in an [Atomic](http://atomicdesign.bradfrost.com/table-of-contents/) way, reflecting both our design and development processes.

Brand assets are mainly for sharing things like logos, colors, icons, and fonts, amongst various projects, and can be split up into multiple sub-packages if we'd like.

### Documentation
We should better utilize [Storybook.js](https://storybook.js.org) to create and document our components.
I suggest selecting a logic layer to both build our framework-specific component library as well as to document the CSS-only framework.

While this does go against the idea of framework agnostic design systems, I think it will reduce overhead of maintaining two sets of documentation, a pure HTML *and* a JS framework variants. We could also look into deriving the pure HTML documentation (with just the CSS class names), from the framework specific one.

### Distribution

Due to the close dependency of the various projects, I think it would make sense to have a monorepo managed by a tool like [Lerna](https://github.com/lerna/lerna) to allow working and publishing changes across projects easier.

### Drawbacks

- The work is non-negligible, but does put us in full control of our design and experience. Allowing us to build highly specialized designs in a consistent aesthetic, without shipping unused styles.
- If we do go the route of completely swappable theme layers, we'd likely have to re-create/repurpose existing libraries and maintain them as the third party designs systems evolve. Upside being that our markup layer, and logic, can stay unchanged.

---

## Prior Art
A good example of such a system in use is [Microsoft's Fabric UI](https://developer.microsoft.com/en-us/fabric#/). The project has an underlying CSS package, and is consumed by several different framework-specific implementation.
Please see how they declare and use a [Button component in React](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Button/DefaultButton/DefaultButton.tsx).

### Design Systems
- [Fabric by Microsoft](https://developer.microsoft.com/en-us/fabric#/)
- [Lightning Design System by Salesforce](https://www.lightningdesignsystem.com)
- [Primer by GitHub](https://primer.style/css)
- [Material Design](https://material.io/develop/web/docs/framework-integration/)

### Frameworks to Consider
- [Tailwind](https://tailwindcss.com/docs/opacity)
- [Tachyons](http://tachyons.io)
- [Basscss](https://basscss.com)
- [Atomic CSS](https://acss.io)

### Logic Layer
The likely de-facto candidate is React. However an interesting candidate to keep an eye on could be [Svelte](https://svelte.dev) if we are interested in producing very small/AMP like publications. The elimination factor for Svelte right now is [complete lack of TypeScript support](https://github.com/sveltejs/svelte/issues/1639).

### Articles
- [Managing technology-agnostic design systems](http://bradfrost.com/blog/post/managing-technology-agnostic-design-systems/)
- [How I Learned to Stop Worrying and Love the Atomic Class](https://medium.com/buzzfeed-design/how-i-learned-to-stop-worrying-and-love-the-atomic-class-98d6ccc45781)
- [5 Takeaways From Using Tailwind CSS In Real Projects](https://nick-basile.com/blog/post/5-takeaways-from-using-tailwind-css-in-real-projects)
- [Functional CSS (FCSS)](http://eng.wealthfront.com/2013/08/20/functional-css-fcss/)
- [Functional Programming, CSS, and your sanity](https://jon.gold/2015/07/functional-css/)

## Alternatives
- We stick to Bulma and create layers of custom components as needed
- We build our own system as outlined above, but don't have layered themes. Instead we decouple as much of our logic as possible from our framework specific components, and share it across multiple UI-specific components. (Here's a [way to theme Material Design](https://glitch.com/~aquatic-gold) for the web)
- Somewhere in between: Use several CSS frameworks to create component variants, and share logic amongst them.

**Comment by alex-ketch** [comment]
To expand on:

> We build our own system as outlined above, but don't have layered themes. Instead we decouple as much of our logic as possible from our framework specific components, and share it across multiple UI-specific components. (Here's a way to theme Material Design for the web)

A real possibility is that even if we do go with a fully custom solution with a swappable theming layers, we still won't be a native citizen of any ecosystem without heavy interference at the component/markup level, and we will always feeling a bit out of place.
An example of this are the skins for Bulma and Bootstrap which are "inspired" by Material and Fluent designs, and they get close to replicating the design systems, but fall short of the real thing.

An option we could explore would be to accept the inevitability of having to use different markup, and work to create "renderless" components. These would encapsulate all of the logic, shareable across all systems, but would require customization at the render layer.
The benefit of this is that we can pull in the official design systems of the respective platform and integrate it with our requirements. Downside being that we'd likely end up changing markup for even moderately complex components.

**Some reading material regarding this topic:**
- https://kentcdodds.com/blog/introducing-downshift-for-react
- https://adamwathan.me/renderless-components-in-vuejs/
- https://github.com/thomashoneyman/purescript-halogen-renderless

---

Bulma themes for:
- Material Design: https://jenil.github.io/bulmaswatch/materia/
- Fluent: https://mubaidr.js.org/bulma-fluent/

Bootstrap themes for:
- Material Design: https://mdbootstrap.com/docs/jquery/components/
- Fluent: https://github.com/mdbootstrap/bootstrap-fluent-design

**Comment by alex-ketch** [comment]
@nokome and I spoke over video yesterday and agreed that we'd like to explore the initial proposal of using Tailwind to develop our own system, and strive to maintain a single content markup structure.
For logic layer we'd like to use React, while decoupling as much of the logic from the view as possible.

We'll go with a semi-monorepo approach, keeping brand assets, documentation, core styles inside this repo. However for the view layer specific variants (e.g `stencila-style-react`), we'll have a separate repository.

I'll be starting work on this today in a new branch.

**Comment by nokome** [comment]
@alex-ketch @jwijay and I spoke over video yesterday and agreed to:

**Comment by alex-ketch** [comment]
@nokome As mentioned on Zulip, in reworking the structure I came to believe that we shouldn't incorporate numbering into the package names, and instead use the `version` field inside the package(.json). I think this is the more idiomatic way of handling and communicating evolution of packages.

As for the current iteration of the `style` repo, I don't think it's worth it to port the current Bulma based styles into the new monorepo structure, and instead have pushed a branch called [`v1`](https://github.com/stencila/designa/tree/v1). This way any back ported changes can be applied and published from that branch.

**Comment by nokome** [comment]
Closing this as done.
