### ISSUE TITLE
CodeExpression outputs not updated after execution

### ISSUE THREAD

**Issue by nokome** [stencila/designa#91]
It seems that the `output` of `CodeExpression`s is not updated after execution. For this code expression:

![Peek 2020-08-16 22-36](https://user-images.githubusercontent.com/1152336/90332461-2818c800-e011-11ea-8c09-d078a90e8747.gif)

the following is sent over Websocket

```js
node: {text: "2 * 2", output: "1,308", programmingLanguage: "r", type: "CodeExpression"}
```
and this is what comes back,

```js
result: {type: "CodeExpression", text: "2 * 2", programmingLanguage: "r", output: 4, duration: 0.007}
```

but the number does not update. Maybe the `executionHandler`?

**Comment by nokome** [comment]
Thanks for this @alex-ketch. It's relatively minor point is that numbers are rendered as disabled `<input type="number">` (?) which is a little confusing

![image](https://user-images.githubusercontent.com/1152336/90347812-a5caeb00-e086-11ea-847d-2d25ec65ba88.png)

**Comment by alex-ketch** [comment]
hmm, can't seem to reproduce in any of my local browsers (Safari, Chrome, Firefox).
Mind sharing more details about your browser+version please @nokome, and I will take a look through SauceLabs shortly.
